### ISSUE TITLE
React error on effect state when uninstanciating a MicroAppComponent

### ISSUE THREAD

**Issue by silverspectro** [calions-app/mf-maestro#5]
Hello,

It seems that there is a state change which makes React complain every time a component is uninstanciated dynamically.

sample error:

![image](https://user-images.githubusercontent.com/2615733/69054402-c4bf2280-0a0b-11ea-8d7d-3836ad64e305.png)

**Comment by alotela** [comment]
this might be due to this problem with HtmlWebpackPlugin:

https://github.com/calions-app/mf-maestro#double-rendering

**Comment by alotela** [comment]
can i close this issue ?

**Comment by silverspectro** [comment]
It still appears some time, but i can't reproduce it consistently.
Very scarce though, do maybe close and reopen if the bug is reproduced ?
